### ISSUE TITLE
TypeError: text is not iterable at formatHTML

### ISSUE THREAD

**Issue by ImTheDeveloper** [telegraf/telegraf#896] opened 2020-02-10 08:38 UTC
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.36
* Node.js Version: 8
* Operating System: Alpine Linux

## Expected Behavior

Please describe the behavior you are expecting

Copy of an animated message to be sent to another chat.

## Current Behavior

What is the current behavior?
Message is not being sent and an error produced in logs.

## Failure Information (for bugs)

Specific error line:

```
TypeError: text is not iterable
    at formatHTML
```

```
Event 'telegram.update.message' received from 'ab880fc1c3b2' node in 'telegram' group(s).
{ update_id: 310674607,
  message: 
   { message_id: 3959,
     from: 
      { id: xxxx,
        is_bot: false,
        first_name: 'xxxx.',
        language_code: 'en' },
     chat: { id: -1001324029056, title: '1', type: 'supergroup' },
     date: 1581323662,
     animation: 
      { file_name: 'animation.gif.mp4',
        mime_type: 'video/mp4',
        duration: 3,
        width: 220,
        height: 164,
        thumb: [Object],
        file_id: 'CgACAgQAAx0CTusUgAACD3deQRWOVvYuLV2U1kc5F5Jc5ncbWAADBgACmMlwUNjay7fcqAriGAQ',
        file_unique_id: 'AgAEBgACmMlwUA',
        file_size: 21480 },
     document: 
      { file_name: 'animation.gif.mp4',
        mime_type: 'video/mp4',
        thumb: [Object],
        file_id: 'CgACAgQAAx0CTusUgAACD3deQRWOVvYuLV2U1kc5F5Jc5ncbWAADBgACmMlwUNjay7fcqAriGAQ',
        file_unique_id: 'AgAEBgACmMlwUA',
        file_size: 21480 } },
  token: 'xxxx' }

[2020-02-10T08:34:26.425] [ERROR] default - TypeError: text is not iterable
    at formatHTML (/app/node_modules/telegraf/markup.js:167:23)
    at Object.document (/app/node_modules/telegraf/core/replicators.js:94:16)
    at Telegram.sendCopy (/app/node_modules/telegraf/telegram.js:410:27)
    at EventLog.issueEventNotification (/app/Bot/Models/EventLog.js:164:36)
    at <anonymous> ' - [../../Bot/Models/EventLog.js:168:17]'

```
### Steps to Reproduce
1. Issue sendCopy against an animated image.

**Comment by Piterden** [comment] 2020-02-10 11:56
`npm up -S`

**Comment by ImTheDeveloper** [comment] 2020-02-12 12:43
Same issue persists. 3.36 was already the latest on master. Should I aim at develop?

**Comment by wojpawlik** [comment] 2020-11-25 13:47
Duplicate of #891

**Closed by wojpawlik** 2020-11-25 13:47 UTC
Labels: bug, help wanted
