### ISSUE TITLE
Loosing scenes

### ISSUE THREAD

**Issue by gunyakov** [telegraf/telegraf#1874] opened 2023-09-10 00:55 UTC
## Context
Telegraf loosing scenes during running in scenes action. 

* Telegraf.js Version: 4.13.1
* Node.js Version: 18.17.1
* Operating System: Linux Mint 21

## Minimal Example Code Reproducing the Issue
I write this scene with midleware to control that telegraf inside scene and scene received events. 
```ts
const scene = new Scenes.BaseScene<Context>("registrationScene");

scene.use(async (ctx, next) => {
  console.log("Inside scene Reg");
  console.log(ctx.scene.session);
  if (typeof ctx.callbackQuery !== "undefined") {
    //console.log("Callback data", ctx.callbackQuery);
  }
  await next();
  //await ctx.send("TXT_PROHIBITED_ACTION");
});

scene.enter(async (ctx) => {
  console.log("Reg scene enter");
  return ctx.send("TXT_REG_STEP_1", "cancel_keyboard");
});

scene.leave((ctx) => {
  return console.log("Reg scene leave");
});

scene.on(message("text"), async (ctx) => {
  console.log(`Text from user`);
});
```
As you see from log that entering to scene was Ok. But somehow when i send text to bot, scene has no any reaction for this text messages and few messages later its no any scene in session. When I send mesaages I just want to see that scene hanlde this events, and i not call any `ctx.scene.leave()` or `ctx.scene.enter()`. But scene become unavailable And scene.leave was not called. 
```bash
Reg scene enter
Processing update 523888869: 3.116ms
{
  userID: 0,
  chatID: 48xxxxxx
  name: 'Oxxx',
  __scenes: {
    current: 'registrationScene',
    state: {},
    expires: 1694306000,
    step: 0
  }
}
Processing update 523888870: 1.978ms
{ userID: 0, chatID: 484xxxx name: 'Oxxx', __scenes: {} }
Processing update 523888871: 1.335ms

```

**Comment by MKRhere** [comment] 2023-09-10 08:01
Did the bot restart in between? Are you using built-in `session()` without a storage adapter?

**Comment by gunyakov** [comment] 2023-09-10 13:09
No, bot wasn restart in between. And yes, I'm using standard telegraf session() without storage adapter.

**Comment by gunyakov** [comment] 2023-09-10 17:22
I also have global midleware what make console.log for session var. My `index.ts` file
```ts
import { Telegraf, session } from "telegraf";
import BotSession from "./middleware/session";
// Create your bot and tell it about your context type
const bot = new Telegraf<Context>(BOT_TOKEN[MODE]);
//Reg default telegraff session
bot.use(session());
//Reg custom session to get users from DB
bot.use(BotSession);
bot.launch({ dropPendingUpdates: true });
```
And code inside `./middleware/session`
```ts
export default async (ctx: Context, next: CallableFunction) => {
    console.time(`Processing update ${ctx.update.update_id}`);
    console.log("Session before actions", ctx.session);
    //Go to next step
    await next();
    console.log("Session after actions", ctx.session);
    // runs after next middleware finishes
    console.timeEnd(`Processing update ${ctx.update.update_id}`);
}
```
And suddenly i have console output
```sh
Session before actions `undefined`
```

But I register `session()` before my middleware and im surprised that `session()` isnt create even empty `ctx.session` object from beginning. And to prevent crash of my code when i try to set some session data like `ctx.session.userID = 3` I need modify code inside `./middleware/session` to be like this
```ts
export default async (ctx: Context, next: CallableFunction) => {
    console.time(`Processing update ${ctx.update.update_id}`);
    console.log("Session before actions", ctx.session);

    //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    if (!ctx.session) ctx.session = {};  

    //Go to next step
    await next();
    console.log("Session after actions", ctx.session);
    // runs after next middleware finishes
    console.timeEnd(`Processing update ${ctx.update.update_id}`);
}
```
May be some problem inside standard `session()` handler???

**Comment by MKRhere** [comment] 2023-09-10 18:12
This is not a problem, but intended behaviour. We don't know what default session should look like, but you can provide it using:

```
bot.use(session({ defaultSession: () => ({}) }));
```

**Comment by gunyakov** [comment] 2023-09-10 22:22
My repo is https://github.com/gunyakov/telegraf-bot-starter where i loose scenes. May be I make something wrong... But scene loosing isnt permanent and happens time to time only.

**Comment by gunyakov** [comment] 2023-09-10 22:32
What mean ttl as option for stage???
I use code what i found in bot examples from telegraff
```ts
const stages = new Scenes.Stage<ExtContext>(
  [accountScene, registrationScene, languageScene], { ttl: 10}
);
```
and when i remove TTL no more scene loosing. =) Issue possible to close but proper manual required.

**Comment by MKRhere** [comment] 2023-09-11 05:50
ttl = time to live. When ttl expires, stage removes the user from scene. I'll close this for now, will document it better.

**Closed as completed by MKRhere** 2023-09-11 05:50 UTC
Labels: question
