### ISSUE TITLE
 Introduce 'deletemessages' Method for Efficient Bulk Message Deletion

### ISSUE THREAD

**Issue by eventvoid** [telegraf/telegraf#1929] opened 2024-01-13 10:23 UTC
**Is your feature request related to a problem? Please describe.**
There is a need for a method to delete multiple messages in a single API call, as the current `deletemessage` method only allows deleting one message at a time.

**Describe the solution you'd like**
I propose adding a new method, `deletemessages`, to the Telegram Bot API (https://core.telegram.org/bots/api#deletemessages), which would allow the deletion of multiple messages in a single request. This enhancement would improve efficiency and streamline the process of managing multiple messages.

**Describe alternatives you've considered**
The existing `deletemessage` method allows the deletion of individual messages, but for scenarios where multiple messages need to be deleted, users currently need to make separate API calls for each message. The proposed `deletemessages` method aims to provide a more efficient solution for this use case.

**Additional context**
No additional context at the moment.

**Comment by MKRhere** [comment] 2024-01-13 10:24
API update is coming soon. Duplicate of #1923

**Closed as completed by MKRhere** 2024-01-13 10:24 UTC
