### ISSUE TITLE
[TypeScript] Property 'settings' does not exist on type 'Telegraf<TelegrafContext>'

### ISSUE THREAD

**Issue by azat-io** [telegraf/telegraf#1178] opened 2020-11-12 20:09 UTC
## Context

* Telegraf.js Version: 3.38.0
* Node.js Version: 12.8.0
* Operating System: MacOS

## Failure Information (for bugs)

Cannot use `settings` prop because of TS error

```ts
import { Telegraf } from 'telegraf'

const bot = new Telegraf(process.env.TELEGRAM_BOT_TOKEN)

bot.settings(ctx => {
  ctx.setMyCommands([
    {
      command: '/foo',
      description: 'foo description',
    },
    {
      command: '/bar',
      description: 'bar description',
    },
  ])
})
```

**Comment by wojpawlik** [comment] 2020-11-21 12:07
Duplicate of #979

**Closed by wojpawlik** 2020-11-21 12:07 UTC
