### ISSUE TITLE
[feature request] Regex-based router commands

### ISSUE THREAD

**Issue by erfanium** [telegraf/telegraf#1126] opened 2020-09-01 13:27 UTC
**Describe the solution you'd like**
Something like:
```ts
bot.command('*', (c) => c.reply('Not Found'))
```

**Comment by imdkbj** [comment] 2020-09-04 14:20
Hey use text event at bottom like as below.

```js

    bot.start(({
        reply
    }) => reply('Hi'));

    bot.command('xyz', (ctx) => ctx.scene.enter('testing'));

    bot.on('text', ({
        reply,
        message: {
            text
        }
    }) => {
		switch(text){
			case('/test'):
				reply('Your\'s command : ' + text);
			break;
			default:
				reply('You just said ' + text);
		}
    });

    bot.catch((e) => console.error('Error', e))

    bot.launch()
```

**Comment by erfanium** [comment] 2020-09-04 20:25
@imdkbj Thanks, But I think using regex-based routes is more clean

**Comment by imdkbj** [comment] 2020-09-05 10:32
Depends on the need, I have given u example how to listen inputs, Rest u better know how to filter. You can close it if solved.

**Comment by erfanium** [comment] 2020-09-05 11:44
@imdkbj This was just a feature suggestion for ragex-based router for commands

**Comment by wojpawlik** [comment] 2020-11-07 12:12
Duplicate of #898. Try `bot.command((c) => c.reply('Not Found'))` or `bot.entity.('command', (c) => c.reply('Not Found'))`

**Closed by wojpawlik** 2020-11-07 12:12 UTC
