### ISSUE TITLE
ctx.scene is undefined on successful_payment

### ISSUE THREAD

**Issue by justmavi** [telegraf/telegraf#1892] opened 2023-10-12 08:12 UTC
> `successful_payment` does not belong to a chat, only to a user. This means it does not get captured by session and subsequently does not belong in a scene.

> Default session key is `user_id:chat_id`, so session is per user per chat. You *can* make session per user globally, and not per chat, by doing: 

```TS
bot.use(session({ getSessionKey: ctx => ctx.from?.id ? String(ctx.from.id) : undefined }));
```
> Be warned, if you do this `successful_payment` will appear inside a scene, but each user will be in their own scene across all their chats that includes the bot.

_Originally posted by @MKRhere in https://github.com/telegraf/telegraf/issues/1891#issuecomment-1759073714_

Didn't help. I'm **STILL** getting this result:

```js
{
  session: {
    __scenes: { current: 'payment', state: {} },
    lang: 'en',
    selectedCategoryId: 2,
    selectedItemId: 10,
    previousMessageId: 2325, 
  },
  scene: undefined
}
```

> successful_payment does not belong to a chat,  only to a user.

ctx.chat isn't null on successful_payment.

I just need to enter user into the scene on successful payment

```js
bot.on('successful_payment', ctx => ctx.scene.enter('successful_payment'))
```

Thats all.

**Comment by justmavi** [comment] 2023-10-12 09:56
@MKRhere, so is this a bug or what now?

**Comment by MKRhere** [comment] 2023-10-12 11:58
> ctx.chat isn't null

My bad.

Let's see more code, and what you expect to happen.

**Comment by justmavi** [comment] 2023-10-12 12:49
There's no point to paste here lot of code, here's the most important: 

```TS
@Scene(SceneNames.PAYMENT_SCENE)
export class PaymentScene {
  constructor(@InjectBot() bot: Telegraf<Context>) {
    bot.on('pre_checkout_query', this.onPreCheckout.bind(this));
    bot.on('successful_payment', this.onSuccessfulPayment.bind(this));
  }

  public async onPreCheckout(ctx: Context) {
    await ctx.answerPreCheckoutQuery(true);
  }

  public async onSuccessfulPayment(ctx: Context) {
    if (ctx.session.phoneNumber) { // true
      await ctx.scene.enter(SceneNames.CALL_SCENE); // ctx.scene is undefined
      return;
    }
  }
}
```

Expected behavior is obvius:
> I just need to enter user into the scene on successful payment

**Comment by MKRhere** [comment] 2023-10-16 10:03
How do you mount `new Stage()`?

**Comment by justmavi** [comment] 2023-10-16 11:17
I don't use it, because I didn't need.

**Comment by MKRhere** [comment] 2023-10-16 12:01
You cannot use scenes without Stage. Stage is what adds ctx.scene.

**Comment by justmavi** [comment] 2023-10-16 12:10
I use them everywhere and only here it doesn't work. Maybe it's implemented somewhere in nestjs-telegraf, but I think no. 
Anyway, I don't need it anymore. If you think that this is not a bug, then close the issue. I don't have time to debug the library right now, maybe I'll check in future. Thank you.

**Comment by MKRhere** [comment] 2023-10-16 15:06
Maybe raise an issue with nestjs-telegraf, since this is not a bug in Telegraf and I'm not able to tell from this example what's the issue in your code. A session and stage is required in your bot for scenes to work. There's no other way around that. I'm closing for now, reopen if you have more information.

**Closed as completed** 2023-10-24 21:05 UTC
