### ISSUE TITLE
heroku deployment

### ISSUE THREAD

**Issue by dongalor** [telegraf/telegraf#590] opened 2019-01-26 23:14 UTC
Still, no progress with deploying to heroku, tried all the answers in this telegraf issues. Is there some recipe for this case?

Thank you in advance!

**Comment by 1blockologist** [comment] 2019-02-02 20:57
There is nothing special about deploying a telegraf bot to Heroku, whats the issue?

**Comment by dotcypress** [comment] 2019-10-30 01:16
Duplicate of #610

**Closed by dotcypress** 2019-10-30 01:16 UTC
Labels: question
