### ISSUE TITLE
Missing typings for "ctx.message"

### ISSUE THREAD

**Issue by bennycode** [telegraf/telegraf#1413] opened 2021-03-19 08:56 UTC
## Context

* Telegraf.js Version: 4.3.0
* Node.js Version: 14.13.1
* Operating System: Windows 10 Professional

## Minimal Example Code Reproducing the Issue

```ts
const {TELEGRAM_BOT_TOKEN} = process.env;
const bot = new Telegraf(TELEGRAM_BOT_TOKEN!);
bot.on('message', async ctx => {
  console.log(ctx.message.text);
  await ctx.reply('👍');
});
```

## Expected Behavior

Being able to access the "text" property from `ctx.message`.

## Current Behavior

> error TS2339: Property 'text' does not exist on type '(New & NonChannel & ChannelChatCreatedMessage) | (New & NonChannel & ConnectedWebsiteMessage) | ... 32 more ... | (New & ... 1 more ... & VoiceMessage)'. Property 'text' does not exist on type 'New & NonChannel & ChannelChatCreatedMessage'.

## Error Message and Logs (`export DEBUG='telegraf:*'`)

I logged `ctx.message` to the console and it looks like this:

```json
{
  "chat": {
    "first_name": "Benny",
    "id": 1008102684,
    "last_name": "Neugebauer",
    "type": "private",
    "username": "benny"
  },
  "date": 1616143210,
  "from": {
    "first_name": "Benny",
    "id": 1008102684,
    "is_bot": false,
    "language_code": "en",
    "last_name": "Neugebauer",
    "username": "benny"
  },
  "message_id": 101,
  "text": "hi"
}
```

Unfortunately, I cannot access the property `text` with TypeScript:

![image](https://user-images.githubusercontent.com/469989/111755256-3544b080-8899-11eb-9d0c-242c89b23f4f.png)

**Comment by wojpawlik** [comment] 2021-03-19 11:15
Duplicate of #1388

**Closed as completed by wojpawlik** 2021-03-19 11:15 UTC
