### ISSUE TITLE
Error: 500: Unsupported http response from Telegram

### ISSUE THREAD

**Issue by danielsalles** [telegraf/telegraf#405] opened 2018-05-01 16:29 UTC
I'm trying to send an audio, but I'm taking this return from the telegram server.
`Error: 500: Unsupported http response from Telegram`

```javascript
const fs = require('fs')
const { promisify } = require('util')
const path = require('path')
const isNull = require('lodash').isNull
const readFileAsync = promisify(fs.readFile)

module.exports = bot => bot.on('message', ctx => {
  const chatId = ctx.update.message.chat.id

  console.log('CHAT ID', chatId)
  console.log('MENSAGEM RECEBIDA', ctx.message.text)

  const someKs = ctx.message.text.match(/K/gi)
  const ksNotNull = k => !isNull(someKs)

  const pathAudios = path.join(__dirname, '../audios/rage.mp3')

  if (ksNotNull(someKs)) {
    readFileAsync(pathAudios)
    .then(d => {
      console.log('FILE', d)
      ctx.replyWithAudio(chatId, d)
    })
    .catch(e => console.log('error', e))
    // ctx.reply(`Contando: ${someKs.length}`)
  }
  else {
    ctx.reply('Não foi encontrado Ks :/')
  }
})

```

**Comment by dotcypress** [comment] 2018-05-04 15:07
Duplicate of #209

**Closed by dotcypress** 2018-05-04 15:07 UTC
