### ISSUE TITLE
How to make the bot read what user says after bot message

### ISSUE THREAD

**Issue by silvanohirtie** [telegraf/telegraf#924] opened 2020-02-27 16:07 UTC
I want the bot to read and store what a user says after the bot's message. Example:

Bot: Insert BTC Wallet Address for the payment
User: 489tyh34078fgh7g4q3t03y3

The 489tyh34078fgh7g4q3t03y3 needs to gets stored in a variable, but I have not Idea how can make the bot read that

**Comment by jacobwaller** [comment] 2020-02-27 16:16
```
bot.on('text', ctx => {
  if(isWaitingForUser) {
    //store message
  }
}
```

**Comment by mynameismental** [comment] 2020-02-27 16:24
> ```
> bot.on('text', ctx => {
>   if(isWaitingForUser) {
>     //store message
>   }
> }
> ```

Sorry, thanks for help but that's not what I asked for, I know the syntax, just I do not know how to do it with this framework

**Comment by jacobwaller** [comment] 2020-02-27 16:28
I don't think I understand your question then. Are you confused on how to store the BTC address into a variable?

You can get the message from ctx
`ctx.message.text`
and then store that into a variable.

**Comment by mynameismental** [comment] 2020-02-27 16:33
> I don't think I understand your question then. Are you confused on how to store the BTC address into a variable?
> 
> You can get the message from ctx
> `let btc_address = ctx.message.text`

I'm trying to store the BTC Address the user types after a CERTAIN bot's message

the bot asks X and waits for the user's reply
users types Y in the chat

bot stores Y in a var

I've used this when creating discord bots, but there's no tutorial, guide or any sort of helpful thing on the internet for this on telegraf

**Comment by mynameismental** [comment] 2020-02-27 16:35
Like:

Bot : Insert your name
User : Adam

Bot : Welcome Adam! 

and adam gets stored in a var called name

**Comment by jacobwaller** [comment] 2020-02-27 16:37
Ah. I was misunderstanding, my bad.

You could set a boolean to true when you're waiting for a response from the user, then do what I said in my first message where when that variable is true, you store the next message from that specific user. Then set the boolean false

**Comment by mynameismental** [comment] 2020-02-27 16:40
Oh right! Thanks a lot

**Comment by jacobwaller** [comment] 2020-02-27 17:08
I am glad to hear that the issue is now solved. Please consider closing this message if you have no further questions

**Comment by IMalyugin** [comment] 2020-03-02 06:21
You’re probably looking for ‘scenes’. Scenes are mechanics, used to create dialogs between the bot and the user, where bot asks a question and awaits for user response.

**Closed** 2020-11-25 00:29 UTC

**Comment by Alazar-dev** [comment] 2022-05-20 07:51
Take a look at this as it is the easiest implementation.

    `function register(ctx, bot) {
          ctx.reply("Insert BTC Wallet Address for the payment: ");
          bot.on("text", async (ctx) => {
               await ctx.telegram
                   .sendMessage(ctx.message.chat.id, ctx.message.chat)
                   .then(() => {
                        ctx.reply(`Your wallet address is: {ctx.update.message.text}`)
                    });
          });
      }`

**Comment by KnorpelSenf** [comment] 2022-05-20 08:12
**DO NOT USE THIS**
> ```
> `function register(ctx, bot) {
>       ctx.reply("Insert BTC Wallet Address for the payment: ");
>       bot.on("text", async (ctx) => {
>            await ctx.telegram
>                .sendMessage(ctx.message.chat.id, ctx.message.chat)
>                .then(() => {
>                     ctx.reply(`Your wallet address is: {ctx.update.message.text}`)
>                 });
>       });
>   }`
> ```

This is an example of what not to do. It is a memory leak which will make your bot consume more and more memory and eventually crash your server. Please don't.

**Comment by jpainam** [comment] 2022-12-14 18:42
> **DO NOT USE THIS**
> 
> > ```
> > `function register(ctx, bot) {
> >       ctx.reply("Insert BTC Wallet Address for the payment: ");
> >       bot.on("text", async (ctx) => {
> >            await ctx.telegram
> >                .sendMessage(ctx.message.chat.id, ctx.message.chat)
> >                .then(() => {
> >                     ctx.reply(`Your wallet address is: {ctx.update.message.text}`)
> >                 });
> >       });
> >   }`
> > ```
> 
> This is an example of what not to do. It is a memory leak which will make your bot consume more and more memory and eventually crash your server. Please don't.

Interested in knowing what will be the correct answer here. You said DO not use it.

**Comment by KnorpelSenf** [comment] 2022-12-14 21:07
Whatever you do, you cannot install more handlers after starting your bot. If you add a new handler upon receiving a message, you are doing something wrong.

There are many different ways to solve the problem differently. On Telegraf, you most likely want to use scenes (but they are kind of hard and not well documented). There are also things like [stateless-question](https://grammy.dev/plugins/stateless-question.html), and if you aren't bound to Telegraf, there are a number of other, more modern abstractions, too.

**Comment by MKRhere** [comment] 2022-12-16 14:42
An example of using scenes to accept answers to questions:

```TS
import { Scenes, session, Telegraf } from "telegraf";
import { message } from "telegraf/filters";

const bot = new Telegraf(token);

bot.use(session());

const question = new Scenes.BaseScene("question");
question.enter(ctx => ctx.reply("Enter token"));
question.on(message("text"), async ctx => {
	// validate
	ctx.session.token = ctx.message.text;
	await ctx.reply("Accepted");
	return ctx.scene.leave();
});

const stage = new Scenes.Stage([question]);
bot.use(stage.middleware());

bot.command("question", ctx => ctx.scene.enter("question"));

bot.launch();
```

If you need to do multiple questions, you should probably use [wizards](https://github.com/feathers-studio/telegraf-docs/blob/master/examples/wizards/wizard.ts).
