### ISSUE TITLE
Autocomplete in VS Code

### ISSUE THREAD

**Issue by DuM4ll3** [telegraf/telegraf#603] opened 2019-02-13 15:41 UTC
Hi,

it seems that IntelliSense is not working for this package in VS Code (v 1.31.1). Does anybody here has the same problem ?

**Comment by Kerita** [comment] 2019-02-20 03:14
the same

**Comment by RaminMT** [comment] 2019-06-27 14:17
I also have same problem in VS Code v1.35.1

**Comment by dotcypress** [comment] 2019-10-29 22:46
Duplicate of #763

**Closed by dotcypress** 2019-10-29 22:46 UTC
Labels: help wanted, investigate
