### ISSUE TITLE
Callbacks called twice

### ISSUE THREAD

**Issue by natario1** [telegraf/telegraf#108] opened 2017-05-19 17:11 UTC
It’s been a few days that, as far as I can tell from logs, some callbacks are called twice. This leads to all kind of inconsistencies.

Is this a telegraf issue? A telegram issue? I will run more tests as soon as possible, just wanted to know if anyone is experiencing this. I’m on `^3.6.4` and that should jump to latest.

I’ll try with `3.6.10` and let you know.

**Comment by natario1** [comment] 2017-05-19 17:36
`3.6.10` seems to work fine.

**Comment by natario1** [comment] 2017-05-19 20:06
@dotcypress Any comments for this? Maybe my first paragraph was misleading, I had `^3.6.4` in node semver, which means I was actually using `3.7.X` (not sure which). I downgraded to `3.6.10` and can’t seem to reproduce the bug, but this means that there’s a bug in `3.7.X`.

This makes sense because I started experiencing the bug recently and `3.7.X` was also released recently.

**Comment by dotcypress** [comment] 2017-05-19 20:10
Hey 👋

Could you provide minimal example code to reproduce this issue?

**Comment by natario1** [comment] 2017-05-19 20:23
I’ll need some work to trace this down to a minimal example. I’ll take a look once I have some time.

This is a line that is surely called twice in my bot for every message:

```javascript
bot.use((ctx, next) => {
    console.log("called twice");
    return next();
});
```

but practically bot is more complex and I’m not sure this alone will reproduce the issue. I only know that this showed up in the last week or so.

**Comment by dotcypress** [comment] 2017-05-19 20:32
Ok, let's wait for example, cause i can't reproduce that.

**Comment by natario1** [comment] 2017-05-19 20:34
Ok man, I’ll be back to you next week hopefully.

**Comment by dotcypress** [comment] 2017-06-24 00:51
Closing for now

**Closed by dotcypress** 2017-06-24 00:51 UTC
Labels: on-hold
