### ISSUE TITLE
[QUESTION] Wizard call from bot.hears

### ISSUE THREAD

**Issue by denarioresearch** [telegraf/telegraf#428] opened 2018-05-22 17:47 UTC
How do I call wizard from `bot.hears('foo',....)` ?

**Comment by Otto-AA** [comment] 2018-05-22 19:08
You can try `bot.hears('foo', () => Stage.enter('wizard-name')`. (Make sure you require Stage before)

**Comment by denarioresearch** [comment] 2018-05-22 19:45
tried this, but I do something wrong. I use wizard bot from [example](https://github.com/telegraf/telegraf/blob/develop/docs/examples/wizard-bot.js). Wizard name is 'super-wizard'. I have removed rows 43 and 45 and called `bot.hears('foo', () => Stage.enter('super-wizard'))` but it doesn't work.

**Comment by Otto-AA** [comment] 2018-05-22 21:05
Maybe the problem is that you deleted lines 43 and 45?

Following code works fine for me:
```javascript
const superWizard = new WizardScene('super-wizard',
  (ctx) => {
    ctx.reply('Step 1', Markup.inlineKeyboard([
      Markup.urlButton('❤️', 'http://telegraf.js.org'),
      Markup.callbackButton('➡️ Next', 'next')
    ]).extra())
    return ctx.wizard.next()
  },
  (ctx) => {
    ctx.reply('Step 2')
    return ctx.wizard.next()
  },
  (ctx) => {
    ctx.reply('Done')
    return ctx.wizard.next()
  }
)

const stage = new Stage([superWizard])
bot.use(session())
bot.use(stage.middleware())
bot.hears('foo', Stage.enter('super-wizard'));
```

**Comment by Otto-AA** [comment] 2018-05-23 16:50
You're welcome :)

If you have no more questions regarding this issue, feel free to close it

**Closed** 2018-12-17 18:08 UTC
Labels: question

**Comment by Andrew3005** [comment] 2020-03-11 13:46
@Otto-AA 
https://github.com/telegraf/telegraf/issues/428#issuecomment-391140449

what is session function?
