### ISSUE TITLE
Crash in network polling

### ISSUE THREAD

**Issue by UrsKramer** [telegraf/telegraf#1877] opened 2023-09-11 10:09 UTC
## Context
After a while of running the bot crashes with this error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "callback" argument must be of type function. Received type number (5000)
at setTimeout (node:timers:141:3)
at new Promise (<anonymous>)
at node:internal/util:361:12
at [Symbol.asyncIterator] (/mybot/node_modules/telegraf/lib/core/network/polling.js:50:27)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Polling.loop (/mybot/node_modules/telegraf/lib/core/network/polling.js:73:30)
at async Telegraf.launch (/mybot/node_modules/telegraf/lib/telegraf.js:189:13)
```

looks like its caused by wrong usage of promisify and setTimeout:

https://github.com/telegraf/telegraf/blob/0ce050b29cb32612570420024eb4ab907a4a901f/src/core/network/polling.ts#L9C1-L9C35

same error as described here
https://stackoverflow.com/questions/51796014/difference-between-util-promisifysettimeout-and-ms-new-promiseresolve

* Telegraf.js Version: 4.13.1
* Node.js Version: v18.17.1
* Operating System: ubuntu 22.04

**Comment by MKRhere** [comment] 2023-09-11 11:05
I'm puzzled by this issue:

![image](https://github.com/telegraf/telegraf/assets/19621208/7decd52c-3ad8-4744-946a-73c8350c8247)

**Comment by UrsKramer** [comment] 2023-09-11 11:07
You are right just checked in node console and works there for me as well 🤔

**Comment by MKRhere** [comment] 2023-09-11 11:11
I checked every major Node version from v20 all the way back to v8 as in the original StackOverflow question, and it works identically. I'm not sure under what circumstance it could behave differently.

**Comment by UrsKramer** [comment] 2023-09-11 11:23
From the util.promisify docs:

> If there is an original[util.promisify.custom] property present, promisify will return its value, see [Custom promisified functions](https://nodejs.org/dist/latest-v18.x/docs/api/util.html#custom-promisified-functions).
> 
> promisify() assumes that original is a function taking a callback as its final argument in all cases. If original is not a function, promisify() will throw an error. If original is a function but its last argument is not an error-first callback, it will still be passed an error-first callback as its last argument.

Looks like `util.promisify(setTimeout`) equals `setTimeout[util.promisify.custom]` as usual promisification would not work with setTimeout due to the callback beeing the first argument.

My guess is that `setTimout` is altered somewhere and the altered version misses the custom promisification.

**Comment by MKRhere** [comment] 2023-09-11 11:26
Are you doing anything funky with the process at all?

1. Are you using any build tools (other than Typescript?)? Could we get details about that?
2. Are you (by mistake?) patching globalThis.setTimeout? Maybe via a dependency? util.promisify will only work as expected with Node's own setTimeout, which has the Symbol. Could we see your dependency list?

**Comment by UrsKramer** [comment] 2023-09-11 11:29
No build tools

Dependencies are:

- axios
- cheerio
- lodash
- sqlite3
- promised-sqlite3
- telegraf

**Comment by MKRhere** [comment] 2023-09-11 11:37
Cannot reproduce with the latest version of these dependencies. Can you post `dependencies` and `devDependencies` from package.json?

**Comment by UrsKramer** [comment] 2023-09-11 11:39
```
"dependencies": {
    "axios": "^1.5.0",
    "cheerio": "^1.0.0-rc.12",
    "lodash": "^4.17.21",
    "promised-sqlite3": "^2.1.0",
    "sqlite3": "^5.1.6",
    "telegraf": "^4.13.1"
  }
```

**Comment by UrsKramer** [comment] 2023-09-11 11:47
Ok I found the culprit. I am running the server with pm2 and the trace option activated. This seemingly overwrites setTimout without adding the custom promisification. Just reproduced it.

**Comment by UrsKramer** [comment] 2023-09-11 12:01
https://github.com/Unitech/pm2/issues/4199

**Comment by MKRhere** [comment] 2023-09-11 12:30
> I found the culprit

Very well done!

> pm2

I remember this. Every two years or so this comes back up again.

```json5
pm2 5.3.0 <- published 6 months ago
└─┬ @pm2/io 5.0.0 <- published 2 years ago
  └─┬ @opencensus/core 0.0.9 <- published 2 years ago
    └─┬ continuation-local-storage 3.2.1 <- published 6 years ago
      └── async-listener 0.6.10 <- published 5 years ago
```

Maybe just time to move on from pm2 if they can't fix their dependencies after 4 years. I will 

This has already been removed in Telegraf's v5 deno branch, but that will take a while to land in stable:
https://github.com/telegraf/telegraf/blob/feat-deno/src/util.ts#L57

I'm not sure whether to reopen #1878 and merge it, since it'll only cause a merge conflict later. But if you feel strongly about it, reopen it and I will merge it. Closing this issue until then.

**Closed as completed by MKRhere** 2023-09-11 12:30 UTC
