### ISSUE TITLE
poll_answer update handler on scene

### ISSUE THREAD

**Issue by whatever-username** [telegraf/telegraf#1538] opened 2021-10-06 19:16 UTC
Hello!
I found something that looks like a bug to me.
poll_answer update handler doesn't work when attached to scene object, but when attached to bot object it works as expected

Looks like @ygorpinto managed to solve this issue by switching to webhook in #1422. I also tried to swtich to webhook, but it doesn't seem to change anything in a case below.

```
const bot = new Telegraf(process.env.token)
var stage = new Stage([testScene()])
bot.use(session())
bot.use(stage.middleware());

bot.start(async (ctx) => {
    await ctx.scene.enter("TestScene")
})

/*
    WORKS
    bot.on('poll_answer', async (ctx) => {
    console.log("poll answer")
})
*/

bot.startPolling()

function testScene() {
    const scene = new Scene('TestScene');
    scene.leave(async (ctx) => {
        console.log("leave")
    });
    scene.enter(async (ctx) => {
        await ctx.replyWithPoll("qqwewq", ['answers', 'adwe'], {
            open_period: 10,
            is_anonymous: false,
        })
    })
    // DOESN'T
    scene.on('poll_answer', async (ctx) => {
        console.log("POlL ANSWER")
    })
    return scene
}
```

Thanks in advance for any clarifications/advices

**Comment by ygorpinto** [comment] 2021-10-08 10:31
@whatever-username Hi, did you create the routes in your app to receive the webhook response?

**Comment by whatever-username** [comment] 2021-10-08 14:45
@ygorpinto Hi!
Yes, I created the routes. Everything else was working as usual, except poll_answer handlers attached to scene

**Comment by Alex-146** [comment] 2021-10-13 13:21
same issue `"telegraf": "^4.4.2"`

problem description: `scene.on(poll_answer)` handler is not working, when user votes in question answer in handled by `bot.on(poll_answer)` if defined

here is my code
```javascript
const { Telegraf, session, Scenes: { BaseScene, Stage } } = require("telegraf")
 
const token = "foobar"
const bot = new Telegraf(token)
 
const scenes = {
  START: "startScene",
}
 
const stage = new Stage([startScene()])
 
bot.use(session())
bot.use(stage.middleware())
 
bot.start((ctx) => {
  ctx.scene.enter(scenes.START)
})
 
bot.on("poll_answer", (ctx) => {
  console.log("bot poll_answer", ctx.pollAnswer)
})
 
bot.launch()
 
function startScene() {
  const scene = new BaseScene(scenes.START)
 
  scene.enter(async (ctx) => {
    await ctx.replyWithPoll("question", ["a", "b"], {
      open_period: 10,
      is_anonymous: false,
    })
  })
  
  scene.on("poll_answer", (ctx) => {
    console.log("scene poll_answer", ctx.pollAnswer)
  })
 
  return scene
}
```

**Comment by itwaze** [comment] 2022-01-28 17:45
the same for `3.39.0` and `4.6.0`
up

**Comment by NormandoHall** [comment] 2022-03-25 23:58
same for 4.7.0

**Comment by NormandoHall** [comment] 2022-03-26 00:15
Maybe related to #1302?

**Comment by dmdin** [comment] 2023-01-18 11:43
I have discovered the problem. It happens because Telegram sends Update object for Poll Answer without __from__ and __chat__ fields. So Telegraf cannot restore session object to use the current scene.

```ts
async function defaultGetSessionKey(ctx: Context): Promise<string | undefined> {
  const fromId = ctx.from?.id
  const chatId = ctx.chat?.id
  if (fromId == null || chatId == null) {
    return undefined
  }
  return `${fromId}:${chatId}`
}
```


This one is default, when we use
```ts
bot.use(session())
```

The solution is to define a custom getSessionKey function

```ts
bot.use(session({
  getSessionKey: async (ctx) => {
    // FIX: pollAnswer doesn't have chatId
    if (ctx.pollAnswer) return ctx.pollAnswer.user.id.toString();
    return ctx.from?.id.toString();
  }
}));
```

**Comment by MKRhere** [comment] 2023-01-18 15:34
@Dikower's reasoning is correct. By default, session key relies on `chat.id` and `from.id`. Telegraf uses this to create one session per chat per user. I would be very cautious about changing session key to be just `from.id`. It can have unexpected behaviour, like the same user being in the same scene across all chats they share with the bot. If this is what you want to happen, then this solution will work. But think carefully before changing `getSessionKey`.

Related tangent: In a future version (v5 or later), we have considered making `defaultGetSessionKey` only return `chat.id` - to match the behaviour of webhooks (Telegram always sends updates per chatId in sequence in webhook mode).

Closing this issue as completed. There's just no good way for Telegraf to reconcile `poll_answer` with scenes, since Telegram doesn't send `poll_answer.chat`. Feel free to open a new issue if you think you have a solution.

**Closed as completed by MKRhere** 2023-01-18 15:34 UTC
