### ISSUE TITLE
Visual Studio Code hints problem (they are partial)

### ISSUE THREAD

**Issue by Petrivah** [telegraf/telegraf#685] opened 2019-06-11 14:22 UTC
**Is your feature request related to a problem? Please describe.**
I think, partially.
I think it's better not to look in documentation every time and see the hint instantly in the IDE.
(I'm using Visual Studio Code)

**Describe the solution you'd like**
I'd like to see Visual Studio Code hint support there.
It is **very** partial at the moment (I see only function **parameters** hints only, and this is sad)
(I have used other libraries for making TG bots, and they had it completely even for VSCode)

**Describe alternatives you've considered**
I used JetBrains WebStorm for a time
(I don't know why, but in WebStorm the hints were, but I steel prefer VSCode IDE)

**Additional context**
Not considering this detail, everything is really good. Thanks you a lot for your product.
Hope you fix this problem. Good luck and thanks for your attention.

**Comment by amaothree** [comment] 2019-07-26 16:00
Yes, I try to install lots of addons from the vscode market and also use the typings from the npm. All not work for telegraf. That is terrible that developing without perfect intellisense

**Comment by foodornt** [comment] 2019-10-05 16:54
oh my god, I'm so happy, I've been trying to fix this for so long, and I'd like to share the solution with you.
Don't do this
```js
const telegraf = require("telegraf");
// Instead, do this
const telegraf = require("telegraf").Telegraf;
```

yeah finally

**Comment by dotcypress** [comment] 2019-10-29 22:46
Duplicate of #763

**Closed by dotcypress** 2019-10-29 22:46 UTC
Labels: discussion, help wanted, investigate
