### ISSUE TITLE
Launch should throw an error on failure

### ISSUE THREAD

**Issue by golergka** [telegraf/telegraf#1189] opened 2020-11-22 23:35 UTC
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Telegraf.js Version: 3.38.0
* Node.js Version: 15.1.0
* Operating System: macos 10.15.7

## Steps to reproduce

I'm launching a Telegraf instance to verify the token. I implement this behaviour by spinning up a bot instance with the token and then trying to launch it, as I expect an invalid token to cause an error.

```Typescript
async function verifyToken(token: string) {
	const userBot = new Telegraf(token)
	try {
		await userBot.launch()
		return true
	} catch (e) {
		return false
	} finally {
		userBot.stop()
	}
}

const result = veryToken('garbage')

console.log('result', result)
```

## Expected Behavior

I expect to see `result false` in console.

## Current Behavior

I see `result true` in console, with Telegraf logging it's failures but eating them up.

## Discussion

I expect that any public API of an action that can be unsuccessful will signal it to the caller. Right now it is impossible to determine, from code, if the current token is valid and can be used to talk to telegram servers.

**Comment by wojpawlik** [comment] 2020-11-23 22:12
Duplicate of #1004

**Closed by wojpawlik** 2020-11-23 22:12 UTC
