### ISSUE TITLE
Heroku integration

### ISSUE THREAD

**Issue by dreamchasersuon** [telegraf/telegraf#487] opened 2018-08-22 16:44 UTC
Hey guys, I wonder if anybody can help me with deployment on the Heroku. 
I used Getting started Heroku guide for a Node.js app. 
1. Prepare a template for a bot. `$ git clone https://github.com/heroku/node-js-getting-started.git`
2. Deploy the template on a Heroku server. `$ git push heroku master`
3. Install npm locally. `$ npm install`
4. Dependencies `$ npm install telegraf --save` 
5. [PROBLEM] Push an update with telegraf integration (example code for this stage below):
```
const Telegraf = require('telegraf');
const express = require('express');
const expressApp = express();

const API_TOKEN = process.env.API_TOKEN || '689******:AAHKqbysDAyHtMJb6pFe5xB5ZiWDlKOVOyo';
const PORT = process.env.PORT || 5000;
const URL = process.env.URL || 'https://gentle-crag-*****.herokuapp.com';

const bot = new Telegraf(API_TOKEN);
bot.telegram.setWebhook(`${URL}/bot${API_TOKEN}`);
expressApp.use(bot.webhookCallback(`/bot${API_TOKEN}`));


bot.start((ctx) => ctx.reply('Welcome'))
bot.command('oldschool', (ctx) => ctx.reply('Hello'))
bot.command('modern', ({ reply }) => reply('Yo'))
bot.command('hipster', Telegraf.reply('λ'))

expressApp.get('/', (req, res) => {
  res.send('Hello World!');
});
expressApp.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
```
After this step, I have a question - how could I start the bot because he doesn't work at all. Can you tell me what should I do to run it with Heroku? 
6. Push updates again. `$ git push heroku master`
7. I ran this app in the browser and got the 'Hello world!' message. 

But the issue is how can I run the bot on the Heroku server? Because I don't receive any updates with bot after this manipulations.

**Comment by Blackscr33n** [comment] 2018-08-23 05:13
Do you have a Procfile configured?
https://devcenter.heroku.com/articles/procfile

**Comment by dreamchasersuon** [comment] 2018-08-23 18:52
The Procfile have this sample of code: `web: node index.js`

Yes, it looks like that:
```
2018-08-23T15:19:46.416470+00:00 heroku[router]: at=info method=POST path="/bot689079142:AAHKqbysDAyHtMJb6pFe5xB5ZiWDlKOVOyo" host=gentle-crag-36941.herokuapp.com request_id=c56048c8-0a0a-4421-86ec-f455a3543ad9 fwd="149.154.167.204" dyno=web.1 connect=0ms service=1ms status=404 bytes=432 protocol=https
2018-08-23T15:52:12.696374+00:00 heroku[web.1]: Idling
2018-08-23T15:52:12.697407+00:00 heroku[web.1]: State changed from up to down
2018-08-23T15:52:13.924795+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2018-08-23T15:52:14.147580+00:00 heroku[web.1]: Process exited with status 143
2018-08-23T18:47:36.189173+00:00 heroku[web.1]: Unidling
2018-08-23T18:47:36.189421+00:00 heroku[web.1]: State changed from down to starting
2018-08-23T18:47:39.262236+00:00 heroku[web.1]: Starting process with command `node index.js`
2018-08-23T18:47:41.697779+00:00 app[web.1]: Listening on 35931
2018-08-23T18:47:42.035530+00:00 heroku[web.1]: State changed from starting to up
2018-08-23T18:47:43.284156+00:00 heroku[router]: at=info method=POST path="/bot689079142:AAHKqbysDAyHtMJb6pFe5xB5ZiWDlKOVOyo" host=gentle-crag-36941.herokuapp.com request_id=31c30e7a-253a-4059-9b70-05d428329cc6 fwd="149.154.167.204" dyno=web.1 connect=1ms service=26ms status=404 bytes=432 protocol=https
2018-08-23T18:47:45.380551+00:00 heroku[router]: at=info method=POST path="/bot689079142:AAHKqbysDAyHtMJb6pFe5xB5ZiWDlKOVOyo" host=gentle-crag-36941.herokuapp.com request_id=201056f6-4d76-44a7-bd83-50a35e94df9c fwd="149.154.167.204" dyno=web.1 connect=1ms service=9ms status=404 bytes=432 protocol=https
2018-08-23T18:47:49.470192+00:00 heroku[router]: at=info method=POST path="/bot689079142:AAHKqbysDAyHtMJb6pFe5xB5ZiWDlKOVOyo" host=gentle-crag-36941.herokuapp.com request_id=65ba168e-767e-4479-bc90-3002487df820 fwd="149.154.167.204" dyno=web.1 connect=1ms service=3ms status=404 bytes=432 protocol=https
2018-08-23T18:47:57.565773+00:00 heroku[router]: at=info method=POST path="/bot689079142:AAHKqbysDAyHtMJb6pFe5xB5ZiWDlKOVOyo" host=gentle-crag-36941.herokuapp.com request_id=5b39eaec-d3b1-4ba6-b652-955b74900cee fwd="149.154.167.204" dyno=web.1 connect=1ms service=9ms status=404 bytes=432 protocol=https
2018-08-23T18:48:13.657014+00:00 heroku[router]: at=info method=POST path="/bot689079142:AAHKqbysDAyHtMJb6pFe5xB5ZiWDlKOVOyo" host=gentle-crag-36941.herokuapp.com request_id=856a2baa-b652-4a75-8ba8-221052969473 fwd="149.154.167.204" dyno=web.1 connect=1ms service=5ms status=404 bytes=432 protocol=https
```

**Comment by Blackscr33n** [comment] 2018-08-31 09:47
This could help you: https://github.com/odditive/heroku-node-telegram-bot

**Comment by dotcypress** [comment] 2019-10-29 23:12
Duplicate of #610

**Closed by dotcypress** 2019-10-29 23:12 UTC
Labels: question
