### ISSUE TITLE
Property 'reply_to_message' does not exist on type 'New & NonChannel & Message'.

### ISSUE THREAD

**Issue by jlubeck** [telegraf/telegraf#1437] opened 2021-04-17 18:12 UTC
## Context

* Telegraf.js Version: 4.3.0
* Node.js Version: v15.14.0
* Operating System: macOS

## Minimal Example Code Reproducing the Issue

```ts
    bot.on('message', async (ctx) => {
        console.log(ctx.message.reply_to_message)
    })
```

## Expected Behavior

reply_to_message should work

## Current Behavior

Getting error `Property 'reply_to_message' does not exist on type 'New & NonChannel & Message'.`

## Error Message and Logs (`export DEBUG='telegraf:*'`)

<img width="683" alt="Screen Shot 2021-04-17 at 2 10 23 PM" src="https://user-images.githubusercontent.com/3067603/115122590-ace42900-9f86-11eb-8421-51f2bebcb876.png">

**Comment by wojpawlik** [comment] 2021-04-18 14:48
Duplicate of #1388

**Closed as completed by wojpawlik** 2021-04-18 14:48 UTC
