### ISSUE TITLE
What's the difference between on text and on message?

### ISSUE THREAD

**Issue by allandiego** [telegraf/telegraf#1434] opened 2021-04-14 01:10 UTC
What's the difference between
```ts
bot.on('message', (ctx, next) => {));
bot.on('text', (ctx, next) => {));
```
both trigger on group / supergroup / private from any sent message

**Comment by wojpawlik** [comment] 2021-04-15 13:48
Duplicate of #1388

**Closed as completed by wojpawlik** 2021-04-15 13:48 UTC
Labels: question

**Comment by wojpawlik** [comment] 2021-04-20 14:30
Related: #1218
