### ISSUE TITLE
replyWithMediaGroup-> Error: 400: Bad Request: wrong remote file identifier specified: Wrong character in the string

### ISSUE THREAD

**Issue by Porkechebure** [telegraf/telegraf#1646] opened 2022-07-02 14:38 UTC
Telegraf.js Version: ^4.8.5
Node.js Version: 14.15.4
Operating System: Win 10 x64, VSCode latest

What happens:
ctx.replyWithMediaGroup can't send base64 images (media group must have a caption
Hot to send correctly?

Expected
Send images

Code to reproduce:
[Pastebin because it's long](https://pastebin.com/Gskg8KEQ)
It has base64 images embedded.
Just replace your token and the bot is ready to be tested and reproduce error.

Notes:
Base64 images are valid.
Pasting to any base64 to image online service produces this:
![image](https://user-images.githubusercontent.com/3466040/177005168-c804e12c-1af3-46a3-9097-72d392fe7bb4.png)

Details of the error:
(node:30228) UnhandledPromiseRejectionWarning: Error: 400: Bad Request: wrong remote file identifier specified: Wrong character in the string
    at Telegram.callApi (c:\pers\sometesttg\node_modules\telegraf\lib\core\network\client.js:265:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
<node_internals>/internal/process/warning.js:44
(node:30228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
<node_internals>/internal/process/warning.js:44
(node:30228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MKRhere** [comment] 2022-07-03 07:00
Closing as a duplicate of #1645, answered there.

**Closed by MKRhere** 2022-07-03 07:00 UTC
