### ISSUE TITLE
WizardScene doesn't execute first step after entering

### ISSUE THREAD

**Issue by aedeveloper** [telegraf/telegraf#1297] opened 2021-01-15 00:46 UTC
## Minimal Example Code Reproducing the Issue

```js
const newQuizWizard = new Scenes.WizardScene(
  "new-quiz-wizard",
  (ctx) => {
    ctx.reply("step 1");
    return ctx.wizard.next();
  },
  (ctx) => {
    ctx.reply("step 2");
    return ctx.scene.leave();
  }
);

const stage = new Scenes.Stage([newQuizWizard]);

bot.use(session());
bot.use(stage.middleware());

bot.command("newquiz", (ctx) => {
  return ctx.scene.enter("new-quiz-wizard");
});

bot.launch();

```

## Expected Behavior
the scene first step should be started after calling `ctx.scene.enter("new-quiz-wizard")`

## Current Behavior

I have to send one more message to the bot to start the first step
however when I set the default wizard option. this issue doesn't occur.

Telegraf version 4.0.0.

**Comment by aedeveloper** [comment] 2021-01-15 14:01
In version 3 it wasn't behave like that.

also I think [the examples](https://github.com/telegraf/telegraf/tree/develop/docs/examples/wizards) and documentation needs some updates.

I know `default` could lead to problems. but what I mean is the behavior changes. it was a little bit confusing.

**Comment by foaudkajj** [comment] 2021-01-17 08:45
I am facing the same problem. It was working properly before updating.
Have you solved it? @aedeveloper

**Comment by aedeveloper** [comment] 2021-01-17 08:55
for now as workaround move first step to `newQuizWizard.enter` as mentioned above by @Autapomorph.

**Comment by foaudkajj** [comment] 2021-01-17 09:05
I tried it. Now it doesn't continue to the second step.

**Comment by linrium** [comment] 2021-01-20 10:57
I have the same problem. I must enter one message.

**Comment by LetItCode** [comment] 2021-02-06 13:56
https://github.com/telegraf/telegraf/blob/develop/src/scenes/base.ts


```ts
enter(...fns: Array<Middleware<C>>) {
  this.enterHandler = compose([this.enterHandler, this.middleware, ...fns])
  return this
}

enterMiddleware() {
  return this.enterHandler
}
```

**Comment by wojpawlik** [comment] 2021-02-06 16:07
Duplicate of #1333

**Closed by wojpawlik** 2021-02-06 16:07 UTC

**Comment by roshankshaw** [comment] 2021-03-03 12:18
Can somebody provide what should be the correct code for the given code in the issue for telgraf 4?

**Comment by SwapnilSoni1999** [comment] 2021-03-30 13:43
> Can somebody provide what should be the correct code for the given code in the issue for telgraf 4?

same it broke again in v4
