### ISSUE TITLE
Support for Vercel edge functions.

### ISSUE THREAD

**Issue by maccman** [telegraf/telegraf#1887] opened 2023-09-28 15:52 UTC
Currently, [telegraf](https://github.com/telegraf/telegraf) relies on a bunch of Node.js APIs like crypto. These are not implemented in edge environments like vercel, edge functions or Cloudflare. 

It's quite useful to have support for the edge given how performant bots need to be.

**Comment by MKRhere** [comment] 2023-09-28 16:19
Duplicate of #1817

**Closed as completed by MKRhere** 2023-09-28 16:19 UTC
